# Generated by Django 3.2.9 on 2021-11-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_library_app', '0003_alter_gamecategories_game_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecategories',
            name='game_categories',
            field=models.PositiveSmallIntegerField(choices=[(8, 'Bijatyki'), (4, 'Zręcznościowe'), (5, 'Strategiczne'), (7, 'Towarzyskie'), (10, 'Symulacje'), (2, 'Sportowe'), (6, 'Wyścigi'), (3, 'Logiczne'), (0, 'Akcji'), (1, 'RPG'), (9, 'Przygodowe')], default=0),
        ),
        migrations.AlterField(
            model_name='gamemode',
            name='game_mode',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Singleplayer'), (1, 'Multiplayer')], default=0),
        ),
    ]
