# Generated by Django 3.2.9 on 2021-11-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_library_app', '0004_auto_20211117_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='sponsored',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamecategories',
            name='game_categories',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Logiczne'), (2, 'Sportowe'), (1, 'RPG'), (6, 'Wyścigi'), (0, 'Akcji'), (7, 'Towarzyskie'), (4, 'Zręcznościowe'), (5, 'Strategiczne'), (10, 'Symulacje'), (8, 'Bijatyki'), (9, 'Przygodowe')], default=0),
        ),
    ]
